name: 构建 Windows 版 FFmpeg (AV3A版本)

on:
  workflow_dispatch:
    inputs:
      ENABLED_DECODERS:
        description: "启用的解码器"
        required: true
        default: 'vorbis opus flac alac pcm_mulaw pcm_alaw mp3 amrnb amrwb aac ac3 eac3 dca mlp truehd libarcdav3a'
      FFMPEG_RELEASE_BRANCH:
        description: "FFmpeg 分支"
        required: true
        default: 'main'

jobs:
  build_Windows_FFmpeg2:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 安装编译工具链
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mingw-w64 nasm pkg-config \
                                gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 \
                                pkg-config-mingw-w64

      - name: 获取 FFmpeg-AV3A 源代码
        run: |
          git clone https://github.com/tongxunlu/ffmpeg-n4.4.2.git ffmpeg
          cd ffmpeg
          git checkout ${{ github.event.inputs.FFMPEG_RELEASE_BRANCH }}
          # 修复权限问题
          chmod -R a+x ffbuild/*.sh
          chmod a+x configure
          chmod a+x compat/windows/makedef

      - name: 编译 Windows 版 FFmpeg
        run: |
          cd ffmpeg
          mkdir -p build
          
          # 设置环境变量
          export PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/lib/pkgconfig
          
          ./configure \
            --arch=x86_64 \
            --target-os=mingw32 \
            --cross-prefix=x86_64-w64-mingw32- \
            --pkg-config=pkg-config \
            --prefix=$PWD/build \
            --enable-muxer=av3a \
            --enable-demuxer=av3a \
            --enable-static \
            --disable-shared \
            --enable-version3
          
          make -j$(nproc)
          make install

      - name: 打包 FFmpeg
        run: |
          cd ffmpeg/build/bin
          mkdir -p ffmpeg-windows
          cp *.exe ffmpeg-windows/
          zip -r ffmpeg-windows.zip ffmpeg-windows

      - name: 上传 FFmpeg 可执行文件
        uses: actions/upload-artifact@v4
        with:
          name: FFmpeg-Windows-AV3A
          path: ffmpeg/build/bin/ffmpeg-windows.zip
