name: Build FFmpeg for Windows

on:
  workflow_dispatch:
    inputs:
      ENABLED_DECODERS:
        description: "Space-separated list of decoders to enable (e.g. libx265 libmp3lame)"
        required: false
        default: "libx265 libfreetype"

jobs:
  build-ffmpeg:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout FFmpeg Source
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            make
            yasm
            nasm
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-x265
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libmp3lame
            mingw-w64-x86_64-libopus
            mingw-w64-x86_64-fdk-aac

      - name: Clone FFmpeg Repo
        run: |
          git clone https://github.com/WoKee/ffmpeg-av3a.git ffmpeg
          cd ffmpeg
          git checkout main

      - name: Configure and Build FFmpeg
        run: |
          export PATH="/mingw64/bin:$PATH"
          mkdir -p $HOME/ffmpeg_build $HOME/bin
          cd ffmpeg

          # Convert ENABLED_DECODERS string to --enable-libxxx flags
          ENABLED_FLAGS=$(for dec in ${{ github.event.inputs.ENABLED_DECODERS }}; do echo --enable-$dec; done)

          ./configure \
            --prefix=$HOME/ffmpeg_build \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$HOME/ffmpeg_build/include -DX265_DEPTH=10" \
            --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
            --extra-libs="-lpthread -lm" \
            --bindir=$HOME/bin \
            --enable-gpl \
            --disable-doc \
            --disable-asm \
            --disable-shared \
            --enable-static \
            --target-os=mingw32 \
            --arch=x86_64 \
            $ENABLED_FLAGS

          make -j$(nproc)
          make install

      - name: Upload ffmpeg.exe
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows
          path: ${{ env.HOME }}/bin/ffmpeg.exe
