name: Build FFmpeg for Ubuntu with AV3A support


on:
  workflow_dispatch:
    inputs:
      ENABLED_DECODERS:
        description: "ENABLED_DECODERS"
        required: true
        default: 'libarcdav3a'
      FFMPEG_RELEASE_BRANCH:
        description: "FFMPEG_RELEASE_BRANCH"
        required: true
        default: 'main'


jobs:
  Build-FFmpeg-Ubuntu:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            yasm \
            cmake \
            git \
            libfreetype6-dev \
            libsdl2-dev \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            zlib1g-dev


      - name: Build FFmpeg with AV3A support
        run: |
          git clone https://github.com/WoKee/ffmpeg-av3a.git ffmpeg-av3a
          cd ffmpeg-av3a





          # 生成配置头文件
            chmod +x configure
            ./configure --disable-everything --enable-avutil
            make libavutil/avconfig.h
      
           


          # Build AV3A static library first
          #cd libavcodec
          #gcc -c -fPIC libarcdav3a.c -o libarcdav3a.o
          #ar rcs libarcdav3a.a libarcdav3a.o
          #cd "$GITHUB_WORKSPACE"
          #cd ffmpeg-av3a

          # 构建AV3A静态库（指定当前目录为头文件搜索路径）
          # cd libavcodec
          # gcc -c -fPIC libarcdav3a.c -o libarcdav3a.o \
          #     -I.. -I../libavutil
          # ar rcs libarcdav3a.a libarcdav3a.o
          # cd ..
          
          
         
          
          # Check if any other scripts need execution permissions
          chmod +x ffbuild/pkgconfig_generate.sh
          if [ -f "version.sh" ]; then
            chmod +x version.sh
          fi

          # Fix ffplay compilation issue
          sed -i 's/#include "FilterEngine.h"//g' fftools/ffplay.c 2>/dev/null || true
          
          # Configure FFmpeg with minimal options for Ubuntu
          ./configure \
            --enable-gpl \
            --enable-version3 \
            --enable-static \
            --disable-shared \
            --disable-ffplay \
            --enable-decoder=${{ github.event.inputs.ENABLED_DECODERS }} \
            --enable-libarcdav3a \
            #--extra-ldflags="-L$PWD/libavcodec -larcdav3a"
            #--extra-cflags="-fPIC" \
            --prefix="$GITHUB_WORKSPACE/ffmpeg-build"


          make -j$(nproc)
          make install


          # Create a single binary with all static libraries
          gcc -o ffmpeg_av3a \
            -Wl,-Bsymbolic \
            -Wl,--whole-archive \
            "$GITHUB_WORKSPACE/ffmpeg-build/lib/libavcodec.a" \
            "$GITHUB_WORKSPACE/ffmpeg-build/lib/libavutil.a" \
            -Wl,--no-whole-archive \
            -lm -lz -lpthread


          # Make the final binary executable
          chmod +x ffmpeg_av3a


      - name: Upload FFmpeg binary
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-av3a-ubuntu
          path: |
            $GITHUB_WORKSPACE/ffmpeg-av3a/ffmpeg_av3a
            $GITHUB_WORKSPACE/ffmpeg-build/include/libavcodec/avcodec.h
            $GITHUB_WORKSPACE/ffmpeg-build/include/libavutil/avutil.h
